/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prog5121poepart3;

/**
 *
 * @author RC_Student_lab
 */
import javax.swing.JOptionPane;
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Usname = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        RegisterAction = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Nme = new javax.swing.JTextField();
        Sname = new javax.swing.JTextField();
        Usr = new javax.swing.JTextField();
        InptPass = new javax.swing.JPasswordField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("REGISTRATION PAGE");

        Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Name.setText("NAME:");

        Surname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Surname.setText("SURNAME:");

        Usname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Usname.setText("USERNAME:");

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setText("PASSWORD:");

        RegisterAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegisterAction.setText("REGISTER");
        RegisterAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("QUIT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegisterAction)
                        .addGap(139, 139, 139)
                        .addComponent(jButton2))
                    .addComponent(Surname)
                    .addComponent(Usname)
                    .addComponent(Password)
                    .addComponent(Name))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(257, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(InptPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addComponent(Usr, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Sname, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Nme, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(Name))
                            .addComponent(Nme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Surname)
                            .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(Usname))
                    .addComponent(Usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(InptPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterAction)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionActionPerformed
         String name= Nme.getText();
        String surname= Sname.getText();
        String username= Usr.getText();
        String pass= InptPass.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(null,"Enter Your Name");
        }
        
        if(surname.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Your Surname");
        }
        
         if(username != null && username.contains("_") && username.length() <=5) {
            JOptionPane.showMessageDialog(null, "Username successfully captured");
        } else{
            JOptionPane.showMessageDialog(null, "Username is not correctly formatted. Please ensure that your username contains an underscore and is no more than 5 characters in length");
           
        }
        if(pass!= null &&! pass.trim().isEmpty()){
            if(pass.length()>=8){
                boolean hasUppercase = false;
                boolean hasDigit = false;
                boolean hasSpecialChar = false;
                
                for(Character c: pass.toCharArray()){
                    if(Character.isUpperCase(c)){
                        hasUppercase = true;
                    } else if(Character.isDigit(c)){
                        hasDigit = true;
                    } else if(!Character.isLetterOrDigit(c)){
                        hasSpecialChar = true;
                    }
                }
                
                if(hasUppercase && hasDigit && hasSpecialChar){
                    JOptionPane.showMessageDialog(null, "Password successfully captured");
                     
                } else{
                    JOptionPane.showMessageDialog(null, "Password is not correctly formatted. Please ensure that the password contains at least 8 characters, a capital letter, a number, and a special character");
                }
            } else {
                JOptionPane.showMessageDialog(null,"Password is too short. It must be atleast 8 characters long");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Password cannot be empty. Please enter a valid password");
        }
        
         new Login().setVisible(true);
    }//GEN-LAST:event_RegisterActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField InptPass;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField Nme;
    private javax.swing.JLabel Password;
    private javax.swing.JButton RegisterAction;
    private javax.swing.JTextField Sname;
    private javax.swing.JLabel Surname;
    private javax.swing.JLabel Usname;
    private javax.swing.JTextField Usr;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
